table countries
	lineageTag: 7c9549d5-23dc-455c-abe6-26feb21f6d1e

	measure GDP = SUMX(RELATEDTABLE(buildings), buildings[gross])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 54d34a5f-e3dd-4be8-9285-aaef7ab6eeaa

	measure workforce = SUMX(RELATEDTABLE(pops), pops[workforce])
		formatString: 0
		lineageTag: 0a39ba56-d66e-4f05-aea5-917e78610d5b

	measure law_workforce =
			CALCULATE(
			    SUM(pops[workforce]),
			    INTERSECT(VALUES(countries[id]), SELECTCOLUMNS(laws, "id", laws[country]))
			)
		formatString: 0
		lineageTag: 5a3dd420-2049-4717-ac82-e9138f0011ba

	column id
		dataType: int64
		formatString: 0
		lineageTag: 31c1b234-68c0-479b-a963-49f4ecb585db
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column definition
		dataType: string
		lineageTag: 545b3df8-3572-479c-b564-218935387f3b
		summarizeBy: none
		sourceColumn: definition

		annotation SummarizationSetBy = Automatic

	column capital
		dataType: int64
		formatString: 0
		lineageTag: 331fefbc-21b7-4ce3-8463-bac67697bbf0
		summarizeBy: sum
		sourceColumn: capital

		annotation SummarizationSetBy = Automatic

	column market
		dataType: int64
		formatString: 0
		lineageTag: 04c735ee-036f-478e-9685-b6fbf6a433eb
		summarizeBy: none
		sourceColumn: market

		annotation SummarizationSetBy = Automatic

	partition countries = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(Root & "\countries.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"definition", type text}, {"capital", Int64.Type}, {"market", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

