table states
	lineageTag: 3d68b751-2b6c-48d1-8eb1-104060697561

	column id
		dataType: int64
		formatString: 0
		lineageTag: 2afec4ca-2d21-44b9-b97e-562f6b1dede5
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column country
		dataType: int64
		formatString: 0
		lineageTag: 41368148-29a6-44eb-92a3-56d116297a10
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: bb59f392-6706-42cc-a287-bd46d807c01f
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column arable_land
		dataType: int64
		formatString: 0
		lineageTag: 445482d1-548b-48d0-87d0-a12437e11692
		summarizeBy: sum
		sourceColumn: arable_land

		annotation SummarizationSetBy = Automatic

	column incorporated
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 850124ee-8316-4334-8e25-553242428716
		summarizeBy: none
		sourceColumn: incorporated

		annotation SummarizationSetBy = Automatic

	column government_revenue
		dataType: string
		lineageTag: 2fe45923-eaa4-4d8e-af90-dfe448eabc86
		summarizeBy: none
		sourceColumn: government_revenue

		annotation SummarizationSetBy = Automatic

	column government_expenses
		dataType: string
		lineageTag: 4c19dee2-d014-4c0f-9939-d655231dbcda
		summarizeBy: none
		sourceColumn: government_expenses

		annotation SummarizationSetBy = Automatic

	column military_wages
		dataType: string
		lineageTag: f45ef070-55f9-42c5-bc7f-7aedde85c3ec
		summarizeBy: none
		sourceColumn: military_wages

		annotation SummarizationSetBy = Automatic

	column military_goods
		dataType: string
		lineageTag: f44a55cc-29ca-4c59-987d-41acd22b0c7f
		summarizeBy: none
		sourceColumn: military_goods

		annotation SummarizationSetBy = Automatic

	partition states = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(Root & "\states.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"country", Int64.Type}, {"region", type text}, {"arable_land", Int64.Type}, {"incorporated", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

