table units
	lineageTag: 6c207d1c-156a-4a32-ba21-ba78294d615c

	column country
		dataType: int64
		formatString: 0
		lineageTag: cc8ec3a1-1bbf-457d-b71c-6aca32346b70
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column culture
		dataType: int64
		formatString: 0
		lineageTag: dfa18924-4463-47cd-95a1-fbdec070256e
		summarizeBy: sum
		sourceColumn: culture

		annotation SummarizationSetBy = Automatic

	column building
		dataType: int64
		formatString: 0
		lineageTag: cf60b737-2b7c-4496-9965-6dd73f826106
		summarizeBy: sum
		sourceColumn: building

		annotation SummarizationSetBy = Automatic

	column manpower
		dataType: int64
		formatString: 0
		lineageTag: c6a6edee-aacb-4f7f-9e5d-882915ec2d89
		summarizeBy: sum
		sourceColumn: manpower

		annotation SummarizationSetBy = Automatic

	column 'type.1'
		dataType: string
		lineageTag: 30c42a9b-2809-4826-9d31-8b341860e431
		summarizeBy: none
		sourceColumn: type.1

		annotation SummarizationSetBy = Automatic

	partition units = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(Root & "\units.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"country", Int64.Type}, {"culture", Int64.Type}, {"building", Int64.Type}, {"manpower", Int64.Type}, {"type", type text}}),
				    #"Split Column by Positions" = Table.SplitColumn(#"Changed Type", "type", Splitter.SplitTextByPositions({17}), {"type.1"})
				in
				    #"Split Column by Positions"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

