select * from (
values -- industry (high = 600)
  ('building_food_industry', 600),
  ('building_textile_mill', 600),
  ('building_furniture_manufactory', 600),
  ('building_glassworks', 600),
  ('building_tooling_workshop', 600),
  ('building_paper_mill', 600),
  ('building_shipyard', 600),
  ('building_arms_industry', 600),
  ('building_artillery_foundry', 600),
  ('building_gizmo_workshop', 600),
  ('building_potion_distillery', 600),
  ('building_distillery', 600),
  ('building_airshipyards', 600),
  -- industry (very_high = 800)
  ('building_chemical_plant', 800),
  ('building_explosives_factory', 800),
  ('building_synthetics_plant', 800),
  ('building_steel_mill', 800),
  ('building_motor_industry', 800),
  ('building_military_shipyard', 800),
  ('building_automotive_industry', 800),
  ('building_electrics_industry', 800),
  ('building_thaumacore_foundry', 800),
  ('building_soulwrought_assembly_plant', 800),
  ('building_cloud_collector', 800),
  ('building_blubber_plants', 800),
  -- farms (low = 200)
  ('building_rye_farm', 200),
  ('building_wheat_farm', 200),
  ('building_rice_farm', 200),
  ('building_maize_farm', 200),
  ('building_millet_farm', 200),
  ('building_livestock_ranch', 200),
  ('building_rice_farm_leechgardens', 200),
  ('building_terrace_farm', 200),
  ('building_mountain_maize_farm', 200),
  ('building_beekeeping', 200),
  ('building_shrimp_farm', 200),
  ('building_gardenback_beetle_ranches', 200),
  ('building_snail_herder_ranch', 200),
  ('building_rotfarm', 200),
  ('building_underfarm', 200),
  ('building_spider_ranch', 200),
  -- mines (medium = 400)
  ('building_iron_mine', 400),
  ('building_lead_mine', 400),
  ('building_sulfur_mine', 400),
  ('building_gold_mine', 400),
  ('building_wishstone_mine', 400),
  ('building_cloudsilver_mine', 400),
  ('building_lapis_mine', 400),
  -- plantations (low = 200)
  ('building_coffee_plantation', 200),
  ('building_cotton_plantation', 200),
  ('building_dye_plantation', 200),
  ('building_opium_plantation', 200),
  ('building_tea_plantation', 200),
  ('building_tobacco_plantation', 200),
  ('building_sugar_plantation', 200),
  ('building_banana_plantation', 200),
  ('building_silk_plantation', 200),
  ('building_rubber_plantation', 200),
  ('building_vineyard', 200),
  ('building_mint_tea_plantation', 200),
  ('building_wyrmfruit_plantation', 200),
  ('building_songberry_plantation', 200),
  ('building_snowrubber_plantation', 200),
  ('building_sunweave_plantation', 200),
  ('building_undertea', 200),
  -- misc resources (low = 200)
  ('building_logging_camp', 200),
  ('building_fishing_wharf', 200),
  ('building_whaling_station', 200),
  ('building_logging_camp_dreamwood', 200),
  ('building_logging_camp_stonewood', 200),
  ('building_haunted_grounds', 200),
  ('building_fishing_wharf_glowfish', 200),
  ('building_fishing_wharf_goldfish', 200),
  ('building_fishing_wharf_rusttails', 200),
  ('building_cactus_farm', 200),
  ('building_fur_hunting_lodge', 200),
  ('building_hunting_lodge', 200),
  ('building_desert_hunting_lodge', 200),
  ('building_winter_hunting_lodge', 200),
  ('building_khus_hunting_lodge', 200),
  ('building_big_game_hunts', 200),
  ('building_hippo_ranches', 200),
  ('building_elephant_hunting_lodge', 200),
  ('building_mammoth_hunting_lodge', 200),
  ('building_ice_pond', 200),
  ('building_ice_cap', 200),
  ('building_squid_squad', 200),
  ('building_seasnake_wharf', 200),
  ('building_krakeneer_outpost', 200),
  ('building_leviathan_outpost', 200),
  ('building_mushroom_logging', 200),
  ('building_underground_wharf', 200),
    -- misc resources (medium = 400)
  ('building_oil_rig', 400),
  ('building_renovated_godsbane_vault', 400),
  ('building_archeology', 400),
  ('building_wishstone_reef', 400),
  ('building_ship_graveyard', 400),
  -- urban (medium = 400)
  ('building_art_academy', 400),
  ('building_power_plant', 400),
  ('building_university', 400),
  ('building_observatory', 400),
  -- infrastructure (very low = 100)
  ('building_questing_office', 100),
  ('building_tavern', 100),
  ('building_trade_center', 100),
  -- infrastructure (low = 200)
  ('building_magic_carpet_store', 200),
  -- infrastructure (medium = 400)
  ('building_port', 400),
  ('building_airship_dock', 400),
  -- infrastructure (very_high = 800)
  ('building_railway', 800),
  ('building_argentum_rail', 800),
  -- other buildings you probably want 0
) as building_costs(building, cost)